server:
  port: 8764
spring:
  application:
    name: eureka-service
  cloud:
    gateway:
      routes:
        - id: Order-Service
          uri: lb://Order-Service
          predicates:
            - Path=/order/**
          filters:          - name: CircuitBreaker
            args:              name: oderService
              fallbackuri: forward:/orderFallback
        - id: Payment-Service
          uri: lb://Payment-Service
          predicates:
            - Path=/payment/**
          filters:
          - name: CircuitBreaker
            args:
              name: paymentService
              fallbackuri: forward:/paymentFallback
eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
